[gcp_service_account]
type = "service_account"
project_id = "eventcheckinsheets"
private_key_id = "46246ceeface0bb1af2a494d307d824a02f0379c"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCVHZKo95YdQ606
7ovzZuZaqn5weqE/EMI5iPVIcxBKvk76gtAE1f/6OT0Dsswo6lz5Z8g+PiEoMXkG
rJALoIISKXxaQoMOlkeJ34yCXAh/w23i6O33Crsh9HYz8SmJBQNA8BGVCoRSSloh
CreHZ0zzlRVSdAE+WzcPgW68jjHJ2IFfyUzRYiz6hakGtm0EEc638YJzSaaqTzbo
5tFiH00RsGTYUHtMcLO0BznMbk2QvjLgeNx7psxkryzObv5oIpSoaAIJFqnmL1DG
Yj6Yf6rhNMSM+cc5btSm8yuI8LqYODK7FlrcdaGCUsjlKraT3qC9MA88pWfABHqG
/gIE7VjZAgMBAAECggEAQSLDYyqPeKYM4B6+pGqQ+g7an2B52hYEeWRxnJ2igrvB
vRzyKAKgx9lD5T8vfjnttgZXCpVSH4AI2Vj8rQ+Gcc+MYdMG85LCmh+7/V+dWM3x
zLop5I1b8/eYwJS6K3+0jaOwUnXfGiEfYKqRQ8TkcMxxHWzN9EKc+Rl1WUkVx5Cv
v3ZbIGsoVRxUw2rZeEqtcq37rdZQBkSPtXs4i1OQcyZwFDPRBAHfJ8BHpshk/JOo
BTLKo39tCpZ6Ai9iTqYR5Iu5xcNBbZI5ChzVJOE+fPf6xNMF+UYxdeo7VU/LiB51
RG1C3zz61c1Qi3G+iUWA5hO+uXkR1aPZrDXSi2tAdwKBgQDSRc7DKUFlDYKnQEv2
P8MHKGDCPms+z9/97gWnJlTqX5tsQPCIRRTU8efF1jjU83XBI0oAOQIuf3UvQRDV
iD8BMO4ZXTdj3ugdSTwmJP8elLO6MEa0C6FqUeVZTc4JbkNduUrZQr2p/YyxHM4Q
IJUyrttt7m5I95Ue5UM07GDe7wKBgQC1iw4VypuLjrLf8Gd11MGMnQrVm38zfE0N
viyick2CvAku0Aayf0PEz4hblGDIEFgemjKIYKc//r5fpR2OFJjMhLyfBX4/CpzA
p+Y7D5/6Ox/sYBcu2B1GGLH4mSMtJI4jUlEmBDBSmXX4TGdPTTI0cGWNDauo9JGd
GVEvHvHEtwKBgDHc1fQXs2c4NfRdXeYOJrxqyc8mKB5kAxTfPb3ubBKMC3o3SBK4
dwEsQC785ssw1IqxSJoW6rqGBQ7omgpY3b/1j3C6Vyk6scZIGJhfC5R/5MLRMeL+
Iw/oTb/IoIRB/n2aM/KjTgCinJtfXkoav+ad6nD+Km7pLxZ9fVtudmZHAoGBAJSX
GVM6vy9t//iNI5FtL3IxA7IskOOKJONPuebIWarcz0NSn3iv877+AmS6wLBfuFBr
81puidY2YomUculc8GfNaTlbXKaqv/xsMGQ8+Lruc8WcLL15xBQgmGKarREA75n3
gVX1bbvdwZIWryRYUfRb3rKh8tPaQejs1OcVk9tnAoGAF9OlWl+T3jMHzFAVNbra
eSuu5eQupJw3Qxq3nGhwceaj0gAVmHIznxSDBSfF8ejkMKgAMaXeqdBH0hF3JcZb
bD+q8vTItuiV3n2pUsWqrKoQa29GhLMf3swNXWg5i1zQnT5YGFxZKL5j0rJQwsPP
KA32rCCOKKFMOg2hT92NLDM=
-----END PRIVATE KEY-----"""
client_email = "streamlit-checkin-bot@eventcheckinsheets.iam.gserviceaccount.com"
client_id = "104281975470942416996"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-checkin-bot@eventcheckinsheets.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
